//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.DBProduct.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_E_ProductLine
    {
        public long ProductLineId { get; set; }
        public string Name { get; set; }
    }
}
