//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.DBPool.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PoolDBContext : DbContext
    {
        public PoolDBContext()
            : base("name=PoolDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_E_Pool> T_E_Pool { get; set; }
    
        public virtual int P_D_CreatePoolIfNotExists(string poolName)
        {
            var poolNameParameter = poolName != null ?
                new ObjectParameter("PoolName", poolName) :
                new ObjectParameter("PoolName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PoolDBContext.P_D_CreatePoolIfNotExists", poolNameParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> P_D_StepPool(string poolName)
        {
            var poolNameParameter = poolName != null ?
                new ObjectParameter("PoolName", poolName) :
                new ObjectParameter("PoolName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("PoolDBContext.P_D_StepPool", poolNameParameter);
        }
    }
}
