//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.DBSpecification.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_E_Specification
    {
        public string SpecificationName { get; set; }
        public string Description { get; set; }
        public int SpecificationVersion { get; set; }
        public decimal ProjectVersion { get; set; }
        public string Controls { get; set; }
        public string Constants { get; set; }
        public bool IsTemplate { get; set; }
        public string DisplayName { get; set; }
    }
}
