//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.DBRelease.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReleaseDBContext : DbContext
    {
        public ReleaseDBContext()
            : base("name=ReleaseDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_E_Deployement> T_E_Deployement { get; set; }
        public virtual DbSet<T_E_ExternalProject> T_E_ExternalProject { get; set; }
        public virtual DbSet<T_E_MainTask> T_E_MainTask { get; set; }
        public virtual DbSet<T_E_Package> T_E_Package { get; set; }
        public virtual DbSet<T_E_ProductLineTask> T_E_ProductLineTask { get; set; }
        public virtual DbSet<T_E_SubTask> T_E_SubTask { get; set; }
    }
}
