//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.DBRelease.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_E_ProductLineTask
    {
        public long ProductLineTaskId { get; set; }
        public long ProductLineId { get; set; }
        public long MainTaskId { get; set; }
    
        public virtual T_E_MainTask T_E_MainTask { get; set; }
    }
}
