//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.DBRelease.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_E_ExternalProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_E_ExternalProject()
        {
            this.T_E_MainTask = new HashSet<T_E_MainTask>();
        }
    
        public long ExternalProjectId { get; set; }
        public string ProjectNumber { get; set; }
        public string ProjectName { get; set; }
        public string Description { get; set; }
        public string Pilote { get; set; }
        public Nullable<System.DateTime> DateObjectiveEnd { get; set; }
        public Nullable<int> Priority { get; set; }
        public short StatusRef { get; set; }
        public short TypeRef { get; set; }
        public bool IsProcessed { get; set; }
        public bool BEImpacted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_E_MainTask> T_E_MainTask { get; set; }
    }
}
