//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.DBRelease.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_E_Deployement
    {
        public long DeployementId { get; set; }
        public long PackageId { get; set; }
        public System.DateTime DeployementDate { get; set; }
        public short EnvironmentDestinationRef { get; set; }
    
        public virtual T_E_Package T_E_Package { get; set; }
    }
}
