//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.DBRelease.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_E_Package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_E_Package()
        {
            this.T_E_Deployement = new HashSet<T_E_Deployement>();
            this.T_E_MainTask = new HashSet<T_E_MainTask>();
        }
    
        public long PackageId { get; set; }
        public Nullable<int> ReleaseNumber { get; set; }
        public short StatusRef { get; set; }
        public bool IsLocked { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<System.DateTime> DeployementObjectifDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_E_Deployement> T_E_Deployement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_E_MainTask> T_E_MainTask { get; set; }
    }
}
