//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.DBRelease.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_E_MainTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_E_MainTask()
        {
            this.T_E_ProductLineTask = new HashSet<T_E_ProductLineTask>();
            this.T_E_SubTask = new HashSet<T_E_SubTask>();
        }
    
        public long MainTaskId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Comments { get; set; }
        public short StatusRef { get; set; }
        public short TaskTypeRef { get; set; }
        public Nullable<System.DateTime> ObjectifCloseDate { get; set; }
        public System.Guid CreationUserGUID { get; set; }
        public System.Guid RequestUserGUID { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<long> PackageId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> OpenedDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<System.DateTime> CanceledDate { get; set; }
        public Nullable<long> ExternalProjectId { get; set; }
    
        public virtual T_E_ExternalProject T_E_ExternalProject { get; set; }
        public virtual T_E_Package T_E_Package { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_E_ProductLineTask> T_E_ProductLineTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_E_SubTask> T_E_SubTask { get; set; }
    }
}
