//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.DBRecord.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_E_Dossier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_E_Dossier()
        {
            this.T_E_Lock = new HashSet<T_E_Lock>();
            this.T_E_Specification = new HashSet<T_E_Specification>();
        }
    
        public long DossierId { get; set; }
        public string Name { get; set; }
        public string ProjectName { get; set; }
        public bool IsTemplate { get; set; }
        public string TemplateDescription { get; set; }
        public string TemplateName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_E_Lock> T_E_Lock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_E_Specification> T_E_Specification { get; set; }
    }
}
