//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.DBRecord.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_E_Specification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_E_Specification()
        {
            this.T_E_Generation = new HashSet<T_E_Generation>();
        }
    
        public long SpecificationId { get; set; }
        public string Name { get; set; }
        public long DossierId { get; set; }
        public decimal ProjectVersion { get; set; }
        public string Controls { get; set; }
        public string Constants { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Comments { get; set; }
        public System.Guid CreatorGUID { get; set; }
    
        public virtual T_E_Dossier T_E_Dossier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_E_Generation> T_E_Generation { get; set; }
    }
}
