//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.DBRecord.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_E_Lock
    {
        public long LockId { get; set; }
        public long DossierId { get; set; }
        public string SessionGUID { get; set; }
        public System.DateTime LockDate { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual T_E_Dossier T_E_Dossier { get; set; }
    }
}
