//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.DBRecord.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_E_Specification
    {
        public long SpecificationId { get; set; }
        public string Name { get; set; }
        public long DossierId { get; set; }
        public decimal ProjectVersion { get; set; }
        public string Controls { get; set; }
        public string Constants { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Comments { get; set; }
    
        public virtual T_E_Dossier T_E_Dossier { get; set; }
    }
}
